[[cursos]]
assessor_slugs = ["wojciech-mittelstaedt-adalberto"]
dataiso = "2023-11-19"
titulo = "Posturas Narcisistas: vocações do sacrifício e vocações do espetáculo"
descricao = """Hoje encontramos muitas vocações que valorizam mais a beleza
externa do que o bem moral.  Padres e freiras no palco ou no altar, fazendo
shows, reunindo multidões. Religiosos e religiosas que buscam o próprio
reconhecimento mais do que serviço ao outro. Nos bastidores dessas atitudes
existe muito sofrimento, decepção e até doenças, como a depressão. Essas são as
posturas narcisistas que fazem parte do mundo contemporâneo onde o ser humano
precisa aparecer e ser reconhecido para sentir que existe."""
cartaz = "img/curso-2022-11-19.png"
link_inscricao = "https://forms.gle/WVoJ17TyJ2S9yvpE7"
online = true

