[[cursos]]
assessor_slugs = ["vagner-sanagiotto"]
dataiso = "2024-04-08"
titulo = "O psicodiagnóstico da experiência religiosa problemática no contexto clínico"
descricao = """O curso é destinado a psicólogos que trabalham nos seminários e casas religiosas, 
formadores/as responsáveis pela formação à vida religiosa consagrada e presbiteral, 
animadores vocacionais, superiores/as."""
cartaz = "img/curso-2024-04-08.png"
link_inscricao = "https://forms.gle/cm6GtHAiFjQjPW9u5"
online = true
