[[contatos]]
nome = "Sao Paulo"
mapa = "localizacao_sp.html"
logradouro = "Rua Prof. José Cucé, 125, 04055-070"
bairro = "Saúde - São Paulo/SP"
fone = "(11) 4371-0935"
whatsapp = "(11) 9 4522-7267"
whatsappNumber = "5511945227267"
whatsappMensagem = "Olá,+gostaria+de+saber+mais+informações+sobre+os+serviços+do+ITA"
email = "acolher_ita@outlook.com"
horarioAtendimento = "Das 9h às 16h"
diasAtendimento = "De segunda a sexta-feira"

[[contatos]]
nome = "Belo Horizonte"
mapa = "localizacao_bh.html"
logradouro = "Rua Salinas, 2101"
bairro = "Santa Tereza - Belo Horizonte/MG"
fone = ""
whatsapp = "(11) 9 5959-6061"
whatsappNumber = "5511945227267"
whatsappMensagem = "Olá,+gostaria+de+saber+mais+informações+sobre+os+serviços+do+ITA"
email = "acolher_ita@outlook.com"
horarioAtendimento = "Das 9h às 16h"
diasAtendimento = "De segunda a sexta-feira"

[[contatos]]
nome = "Curitiba"
mapa = "localizacao_bh.html"
logradouro = "Rua Senador Xavier da Silva, 488, 3.° andar, sala 301"
bairro = "Centro Cívio - Curitiba/PR"
fone = "(41) 99577-4144"
whatsapp = "(11) 9 4522-7267"
whatsappNumber = "5511945227267"
whatsappMensagem = "Olá,+gostaria+de+saber+mais+informações+sobre+os+serviços+do+ITA"
email = "acolher_ita@outlook.com"
horarioAtendimento = "Das 9h às 17h"
diasAtendimento = "De segunda a sexta-feira"

