[[cursos]]
assessor_slugs = ["frei-josé-moacyr-cadenassi"]
dataiso = "2023-05-13"
titulo = "Lectio Divina: Leitura Orante da Palavra de Deus"
descricao = """Neste momento de 'rezar a palavra', que é o objetivo da 'Lectio Divina', 
o(a) orante experimenta a força vivificadora da Palavra de Deus, mediante os quatro passos: 
1) Leitura; 2) Meditação; 3) Oração; e 4) Contemplação. É um exercício de transposição, 
pela leitura, para o conteúdo da perícope bíblica escolhida para a vivência, resultando 
no aprendizado, louvor e compromisso de vida de quem, peregrino(a), 
corresponde à obra da graça divina na história."""
cartaz = "img/curso-2023-05-13-a.png"
link_inscricao = "https://forms.gle/vsNYMZ6Q2L3NtQJN8"
online = false

[[cursos]]
assessor_slugs = ["wojciech-mittelstaedt-adalberto"]
dataiso = "2023-04-25"
titulo = "O impacto das mídias sociais e da Internet na VRC e sacerdotal"
descricao = """Como o uso das mídias sociais afetam as rotinas e avanços da vida religiosa consagrada e plesbiteral."""
cartaz = "img/curso-2023-04-25.png"
link_inscricao = "https://forms.gle/GNKtbYyCjFppXx8B9"
online = true

