# Imagens
# =======
#
# Imagens do membros devem ser quadradas e com tamanho superior a 400x400 (idealmente 600x600)
#
# Grupos para classificação:
#  psicoespiritual
#  psicoterapêutico
#  psicanalítico
#  outras
#
# Membros ativos 2021-11-26
# =========================
#
# Anamelia Alvarenga Nascimento
# Edênio Valle Pe. (vice-presidente honorário)
# Adalberto Wojciech Mittelstaedt
# Enio Brito Pinto
# Flávia Moreira Ribeiro
# Ir. Elizete Moura dos Santos
# Jyothi Joseph Satyanapalli
# Lillian M. P. de Arruda Zamith
# Lourdes Degrandis
# Maria de Fátima Rolim Rosa
# Maria Ondina da Silva Peruzzo
# Maria Silva Mourão
# Maruzania Soares Dias
# Rosa Eliza da Silva
# Eduardo Augusto Galindo de Lima
# Francisco Glenio de Almeida
# Wellington Heleno da Silva

[[membros]]
ativo = true
grupo = "psicoterapêutico"
avatar = "maria-da-conceicao-machado-silva-rosa.jpg"
masculino = false
slug = "maria-da-conceicao-machado-silva-rosa"
nome = "Maria da Conceição Machado Silva Rosa"
titulo = "Psicóloga Clínica"
CRP = "06/98755"
descricao = """
Possui Especialização em Cuidados Primários em Saúde Mental pela UNIFESP-SP
e Especialização em Psicopatologia e Saúde Pública pela Faculdade de Saúde
Pública – USP."""
areas = [
  "Saúde mental",
  "Psicoterapia individual",
  "Psicologia Clínica",
  "Psicologia Institucional",
  "Psicopatologia e saúde pública"
]

[[membros]]
ativo = true
grupo = "psicoterapêutico"
avatar = "elizete-moura-dos-santos.jpg"
masculino = false
slug = "elizete-moura-dos-santos"
nome = "Ir. Elizete Moura dos Santos"
titulo = "Psicóloga"
CRP = "06/177899"
descricao = """
Licenciada em Filosofia; Psicóloga Clínica; Especialista em Adolescência
e Juventude; Associada ao Corpo Freudiano Escola de Psicanálise de João
Pessoa/PB."""
areas = [
  "Psicologia Clínica",
  "Psicoterapia individual",
  "Formações",
  "Palestras",
  "Coordenação e interação grupal"
]

[[membros]]
ativo = true
grupo = "administrativo"
avatar = "paulo-sergio-frederico.jpg"
masculino = true
slug = "paulo-sergio-frederico"
nome = "Paulo Sérgio Frederico"
titulo = "Secretário"
descricao = ""
areas = ["Organização dos eventos"]

[[membros]]
ativo = true
grupo = "psicoterapêutico"
avatar = "flavia-moreira-ribeiro.jpg"
masculino = false
slug = "flavia-moreira-ribeiro"
nome = "Flávia Moreira Ribeiro"
titulo = "Psicóloga Clínica"
CRP = "06/108.831"
descricao = """
Mestre em Ciência da Religião - PUC SP, Psicóloga especialista em psicologia
junguiana e Perita do Tribunal Eclesiástico de Aparecida – SP"""
areas = [
  "Psicoterapia individual adulto",
  "Psicoterapia de casal",
  "Cursos",
  "Palestras",
  "Workshops"
]

[[membros]]
ativo = true
grupo = "psicoterapêutico"
avatar = "eduardo-augusto-galindo-de-lima.jpg"
masculino = true
slug = "eduardo-augusto-galindo-de-lima"
nome = "Eduardo Augusto Galindo de Lima"
titulo = "Psicólogo Clínico"
CRP = "06/82462"
descricao = "Especialista em Psicoterapia Breve"
areas = [
  "Psicoterapia de adultos",
  "Grupos e casal",
  "Workshop",
  "Assessorias de grupos e palestras"
]

[[membros]]
ativo = true
grupo = "psicoterapêutico"
avatar = "enio-brito-pinto.jpg"
masculino = true
slug = "enio-brito-pinto"
nome = "Ênio Brito Pinto"
titulo = "Psicólogo"
CRP = "06/14675-7"
descricao = """
Gestalt-terapeuta, psicopedagogo, escritor, professor, mestre e doutor em
Ciências da Religião e pós-doutor em Psicologia Clínica pela PUC/SP. Autor,
dentre outros, do livro “Os Padres em Terapia: Esclarecendo singularidades”
(Editora Ideias e Letras, 2012)."""
areas = [
  "Psicoterapia individual",
  "Psicoterapia de grupo",
  "Sexualidade", 
  "Coordenação de grupos de reflexão",
  "Cordenação de oficinas de convívio e de criatividade"
]

[[membros]]
ativo = true
avatar = "lillian-maria-penteado-de-arruda-zamith.jpg"
grupo = "psicoterapêutico"
masculino = false
slug = "lillian-maria-penteado-de-arruda-zamith"
nome = "Lilian Maria Penteado de Arruda Zamith"
titulo = "Psicóloga clínica e Hospitalar"
CRP = "06/35767-8"
descricao = """
Especialista em Psicologia corporal pelo Instituto Sedes
Sapientiae. Aperfeiçoamento em Psicologia Winnicotiana do Amadurecimento.
TCC – Terapia Cognitiva Comportamental."""
areas = [
  "Psicoterapia individual",
  "Casais",
  "Grupos",
  "Vivências",
  "Cursos",
  "Palestras"
]

[[membros]]
ativo = true
grupo = "psicoespiritual"
avatar = "joao-edenio-reis-valle.jpg"
masculino = true
slug = "joao-edenio-reis-valle"
nome = "João Edênio Reis Valle"
titulo = ["Doutor em Psicologia", "Presidente honorário do ITA"]
titulo_es = ["Doctor en Psicología", "Presidente de Honor del ITA"]
descricao = """
Graduação em Psicologia pelo Instituto de Psicologia da pontifícia Universidade
Salesiana (Roma); doutorado no Instituto de Psicologia da Universidade
Salesiana de Roma e na Bélgica. De volta ao Brasil trabalhou em vários setores
da PUC-SP e deu início a atividades de assessoria e direção nas principais
organizações da Igreja católica no Brasil e na América Latina. É autor de
muitos livros e artigos na área de Psicologia, Educação, Vida Religiosa
e Pastoral."""
descricao_es = """
Licenciada en Psicología por el Instituto de Psicología de la Universidad Pontificia
Salesiana (Roma); doctorado en el Instituto de Psicología de la Universidad
Salesiana de Roma y Bélgica. De vuelta en Brasil, trabajó en varios sectores.
en la PUC-SP e inició actividades de asesoría y gestión en las principales
organizaciones de la Iglesia Católica en Brasil y América Latina. es el autor de
muchos libros y artículos en el campo de la Psicología, Educación, Vida Religiosa
y pastoral."""
areas = []

[[membros]]
ativo = true
grupo = "psicanalítico"
avatar = "francisco-glenio-de-almeida.jpg"
masculino = true
slug = "francisco-glenio-de-almeida"
nome = "Francisco Glenio de Almeida"
titulo = "Psicoterapeuta"
CRP = ""
descricao = """
Formado em filosofia (Unifai), Teologia (N. Sra. Assunção), Aconselhamento
e Orientação familiar. Pós-graduado em Psicoterapia Psicanalitica
(Cepsi-Unip)."""
areas = [
  "Atendimento individual",
  "Atendimento familiar",
  "Atendimento de casais",
  "Psicoterapia psicanalítica"
]

[[membros]]
ativo = true
grupo = "psicoterapêutico"
avatar = "lourdes-degrandis.jpg"
masculino = false
slug = "lourdes-degrandis"
nome = "Lourdes Degrandis"
titulo = "Psicóloga Clínica"
CRP = "06/35768-6"
descricao = """
Psicóloga Clínica com especialização em Psicoterapia Corporal pelo Instituto
Sedes Sapientiae, Psicossomática pelo Instituto Sedes Sapientiae, EMDR
(Dessensibilizarão e Sensibilização através de movimentos Oculares) pela
Sociedade Brasileira e Libero Americana de EMDR e Neuropsicologia pelo CDN
- Centro de Diagnóstico Neuropsicológico - UNIFSP."""
areas = [
  "Atendimento de adultos (individual e grupos)",
  "Assessoria a instituições",
  "Workshop",
  "Cursos",
  "Palestras"
]
notas = [
  "Artigo na Revista Convergência",
  "Trabalho sobre Gerações- Formadores - PUC-SP e ITESP",
  "Formadores - OSIB",
  "Formadores - CRB-SP",
  "Juninter - CRB-SP"
]

[[membros]]
ativo = true
grupo = "x"
avatar = "maria-de-fatima-naves.jpg"
masculino = false
slug = "maria-de-fatima-naves"
nome = "Mária de Fátima Naves"
titulo = "Psicóloga Clínica"
CRP = "06/40520-0"
descricao = """
Especialização em Análise Transacional, Psicodrama e Psicanálise das
Configurações Vinculares."""
areas = [
  "Psicoterapia individual",
  "Psicoterapia de grupo",
  "Coordenação de grupos de reflexão em Psicanálise dos Vínculos",
  "Integração grupal"
]

[[membros]]
ativo = true
grupo = "psicoterapêutico"
avatar = "maria-de-fatima-rolim-rosa.jpg"
masculino = false
slug = "maria-de-fatima-rolim-rosa"
nome = "Maria de Fátima Rolim Rosa"
titulo = "Psicóloga Clínica"
CRP = "06/34959-7"
descricao = """
Especialização e aperfeiçoamento em Gestalt-Terapia, Psicologia Junguiana
e Corporal, Psicologia Winnicotiana e Psicanálise das Configurações
Vinculares."""
areas = [
  "Psicoterapia Individual",
  "Psicoterapia de grupal",
  "Workshop",
  "Assessoria a instituições",
  "Acompanhamento de grupos",
  "Cursos",
  "Palestras"
]

[[membros]]
ativo = true
grupo = "psicoterapêutico"
avatar = "maria-ondina-da-silva-peruzzo.jpg"
masculino = false
slug = "maria-ondina-da-silva-peruzzo"
nome = "Maria Ondina da Silva Peruzzo"
titulo = "Especialista em Psicologia Clínica"
CRP = "06/23032"
descricao = """
Especialização em coordenação de grupos e grupoterapia, membro efetivo do
NESME. Especialização em Rorscharch e outras técnicas projetivas; membro
efetivo da Sociedade Brasileira de Rorschach."""
areas = [
  "Psicoterapia individual",
  "Psicoterapia de grupo",
  "Psicodiagnóstico individual",
  "Psicodiagnóstico de grupo",
  "Assessoria de grupos em instituições"
]

[[membros]]
ativo = true
grupo = "psicoterapêutico"
avatar = "maria-silva-mourao.jpg"
masculino = false
slug = "maria-silva-mourao"
nome = "Maria Silva Mourão"
titulo = "Especialista em Psicologia Clínica"
CRP = "06/16774"
descricao = """
Mestre em Psicologia Clínica pela PUC-SP; especialista em espiritualidade pela
Gregoriana – Roma; artigos publicados na área da Vida Religiosa Consagrada. Foi
membro da Equipe de Reflexão dos psicólogos da CRB Nacional por quatorze
anos."""
areas = [
  "Psicoterapia individual",
  "Psicoterapia de grupo",
  "Assessorias a congregações religiosas"
]

[[membros]]
ativo = true
grupo = "psicoterapêutico"
avatar = "maruzania-soares-dias.jpg"
masculino = false
slug = "maruzania-soares-dias"
nome = "Maruzânia Soares Dias"
titulo = "Psicanalista / Psicóloga Clinica"
CRP = "06/53301-7"
descricao = """
Mestre em Ciências da Religião PUC-SP; graduada em Psicologia pela PUC-SP;
membro da IF-EPFCL – Fórum SP (Internacional dos Fóruns – Escola de Psicanálise
dos Fóruns do Campo Lacaniano – Fórum São Paulo)."""
areas = [
  "Atendimento clínico",
  "Assessorias a grupos e instituições",
  "Conferências"
]

[[membros]]
ativo = true
grupo = "psicoterapêutico"
avatar = "rosa-eliza-da-silva.jpg"
masculino = false
slug = "rosa-eliza-da-silva"
nome = "Rosa Eliza da Silva"
titulo = "Especialista em Psicologia clínica"
CRP = "06/15430"
descricao = """
Psicanalista com formação no Sedes Sapientiae. Mestre em Ciências da Religião
pela PUC-SP. Membro da Associação Brasileira de Rorschach (ASBRO). Membro da
Associação Brasilei-ra de Orientação Profissional (ABOP)."""
areas = [
  "Psicodiagnóstico",
  "Psicoterapia psicanalítica individual",
  "Orientação Vocacional/Profissional",
  "Orientação de Carreira"
]

[[membros]]
ativo = true
grupo = "psicoterapêutico"
avatar = "anamelia-alvarenga-nascimento.jpg"
masculino = false
slug = "anamelia-alvarenga-nascimento"
nome = "Anamelia Alvarenga Nascimento"
titulo = "Psicóloga"
CRP = "06/89645"
descricao = """Pós-Graduada com especialização em Saúde Mental e 
Reforma Psiquiátrica pelo Instituto Sedes Sapientiae.
Sólidos conhecimentos sobre ECA, SUAS, SUS, Reforma Psiquiátrica, 
Luta Antimanicomial, Lei Maria da Penha, Triagem Psicossocial. 
Coordenação de grupos, palestras, grupos operativos e grupos psicoterapêuticos.
Experiência com articulação intersetorial, sociassistencial e da atenção psicossocial.
Experiência como docente presencial e EAD, participação com poster/comunicação oral/
rodas de conversa em Congressos, Simpósios e Seminários sobre Saúde Mental, 
Saúde Pública, Psicanálise e Direitos Humanos.
"""
areas = [
  "Coordenação de grupos",
  "Palestras",
  "Grupos operativos e grupos psicoterapêuticos",
  "Assessorias de grupos e palestras"
]

[[membros]]
ativo = true
grupo = "psicoterapêutico"
avatar = "wellington-heleno-da-silva.jpg"
masculino = true
slug = "wellington-heleno-da-silva"
nome = "Wellington Heleno da Silva"
titulo = "Psicólogo Clínico"
CRP = "06/10292"
descricao = """
Especialização em Psicoterapia Psicanalítica – CEPSI/UNIP; MBA em Gestão de
Pessoas e Liderança – BSP (Business School of São Paulo); Graduado em Teologia,
Instituto Pio XI; Curso de Filosofia no Instituto Filosófico do Mosteiro de São
Bento; Curso de Psicologia de Grupo e Aconselhamento de Adolescentes e Jovens.
Membro efetivo do Instituto Acolher – ITA."""
areas = [
  "Psicoterapia individual",
  "Psicoterapia de grupo (adolescentes, adultos e casais)",
  "Grupos psicanalíticos de reflexão e discussões",
  "Palestras e assessorias de formação para grupos e instituições"
]

[[membros]]
ativo = true
grupo = "psicoterapêutico"
avatar = "wojciech-mittelstaedt-adalberto.jpg"
masculino = true
slug = "wojciech-mittelstaedt-adalberto"
nome = "Wojciech Mittelstaedt (Adalberto)"
titulo = "Psicopedagogo / Psicólogo Clínico"
CRP = "06/99753"
descricao = """
Padre da Congregação do Verbo Divino; Doutor em Ciências da Religião (PUC/SP)
com enfoque em Psicologia da Religião; Mestre em Teologia pela Universidade
KUL, na Polônia; graduado em Psicologia (Universidade São Marcos – SP);
especializado em Psicopedagogia; aperfeiçoamento em tratamento da Dependência
Química pela UNIFESP; Membro do Instituto Acolher – ITA."""
areas = [
  "Psicologia clínica",
  "Assessorias",
  "Palestras",
  "Formação religiosa",
  "Espiritualidade sacerdotal",
  "Renovação religiosa",
  "Tratamento dos vícios"
]

[[membros]]
ativo = true
grupo = "outras"
avatar = "jyothi-joseph-satyanapalli.jpg"
masculino = false
slug = "jyothi-joseph-satyanapalli"
nome = "Jyothi Joseph Satyanapalli"
titulo = "Massoterapêuta"
descricao = """
Missionária indiana do PIME, tem 
contato com a massagem desde criança, 
quando aplicava as técnicas em seus 
pais e avós"""
areas = [
  "Massoterapia", 
  "Drenagem linfática",
  "Quick massagem",
  "Bambu terapia",
  "Pedras quentes",
  "Modelação",
  "Redução",
  "Limpeza facial", 
  "Terapia Eletromagnético",
  "Reflexologia",
  "Floral de Bach"
]

[[membros]]
ativo = true
grupo = "psicoterapêutico"
avatar = "leonel-gomes-da-silva.jpg"
masculino = true
slug = "leonel-gomes-da-silva"
nome = "Leonel Gomes da Silva"
titulo = "Graduando em Psicologia"
CRP = "x"
descricao = """
Master em Psicologia do Desenvolvimento da criança e do Adolescente pela Universidade de Santiago de Compostela 
Especializacao em Neuropsicologia pela Faculdade Rui Barbosa, Salvador, BA. Graduação em Filosofia pela FAJE,
Graduação em Teologia pela FaJe. Graduando em Psicologia pela Mackenzie."""
areas = [
  "Orientação Educacional",
  "Pastoral",
  "Projetos Sociais"
]
areas_es = [
 "Orientación educativa",
 "Pastoral",
 "Proyectos sociales"
]

[[membros]]
ativo = true
grupo = "psicoterapêutico"
avatar = "marilda-santos-de-souza.jpg"
masculino = true
slug = "marilda-santos-de-souza"
nome = "Marilda Santos de Souza"
titulo = "Bacharel em Psicologia"
CRP = "x"
descricao = """
"""
areas = [
  "x",
  "y"
]

[[membros]]
ativo = true
grupo = "outras"
avatar = "jose-moacyr-cadenassi.jpg"
masculino = true
slug = "jose-moacyr-cadenassi"
nome = "José Moacyr Cadenassi"
titulo = "Integrador Espiritual"
descricao = """
Frade e presbítero da Ordem dos Frades Menores Capuchinhos do Estado de São Paulo."""
areas = []



[[membros]]
ativo = true
grupo = "psicoterapêutico"
avatar = "sergio-lucas-camara.jpg"
masculino = true
slug = "sergio-lucas-camara"
nome = "Sérgio Lucas Câmara"
titulo = "Psicólogo"
CRP = "06/107924"
descricao = """
Padre e pároco da Arquidiocese de São Paulo, Doutor em Psicologia Clínica pela PUC de São Paulo, 
Mestrado em Psicologia Clínica pela PUC de São Paulo, Mestre em Teologia Pastoral pela UNIFAI de São Paulo.
Publicações: CAMARA, S. L.; VALE, T.G. Assistência espiritual. In: CASTILHO, R. K.; SILVA, V.C.S.; PINTO, C.S. 
Manual de Cuidados Paliativos da Academia Nacional de Cuidados Paliativos - ANCP, 3ª. ed. Rio de Janeiro: Atheneu, 2021.
CAMARA, S. L; VALE, T. G.; BASSANI, M. A. A preparação dos padres para lidarem com a situação de morte no Brasil: 
uma revisão documental e crítica. Revista de Cultura Teológica. São Paulo, n. 93, pp. 322-347, 2019."""
areas = [
  "Psicoterapia com enlutados",
  "Psicologia Clínica"
]

